apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/dev-null-loop/private-oke-karpenter.git
    targetRevision: main
    path: gitops/c/kpo
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  ignoreDifferences:
    - group: oci.oraclecloud.com
      kind: OCINodeClass
      name: karpenter-general
      jsonPointers:
        - /spec/sshAuthorizedKeys
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
