apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpenter-general
spec:
  template:
    spec:
      expireAfter: Never
      terminationGracePeriod: 120m
      nodeClassRef:
        group: oci.oraclecloud.com
        kind: OCINodeClass
        name: karpenter-general
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: oci.oraclecloud.com/instance-shape
          operator: In
          values:
            - VM.Standard.E5.Flex
  disruption:
    budgets:
      - nodes: 5%
    consolidateAfter: 60m
    consolidationPolicy: WhenEmpty
  limits:
    cpu: 4
    memory: 32Gi
