apiVersion: oci.oraclecloud.com/v1beta1
kind: OCINodeClass
metadata:
  name: karpenter-general
spec:
  preBootstrapInitScript: IyEvdXNyL2Jpbi9lbnYgYmFzaAojIEthcnBlbnRlciBQcm92aWRlciBPQ0kgT0tFIGJvb3RzdHJhcCBjb21wYXRpYmlsaXR5IHNoaW0uCiMKIyBFeHBvcnQgT0tFIGJvb3RzdHJhcCBtZXRhZGF0YSBpbnRvIHRoZSBlbnZpcm9ubWVudCBiZWZvcmUgT3JhY2xlJ3MKIyBzdGFuZGFyZCBPS0Ugd29ya2VyIGJvb3RzdHJhcCBlbnRyeXBvaW50IHJ1bnMuCgpzZXQgLW8gZXJyZXhpdApzZXQgLW8gbm91bnNldApzZXQgLW8gcGlwZWZhaWwKCk1EX1VSTD0iaHR0cDovLzE2OS4yNTQuMTY5LjI1NC9vcGMvdjIvaW5zdGFuY2UvbWV0YWRhdGEiCkFVVEhfSERSPSJBdXRob3JpemF0aW9uOiBCZWFyZXIgT3JhY2xlIgoKZmV0Y2hfbWQoKSB7CiAgbG9jYWwga2V5PSIkMSIKICBjdXJsIC1zZkwgLUggIiR7QVVUSF9IRFJ9IiAtLWNvbm5lY3QtdGltZW91dCAyIC0tbWF4LXRpbWUgNSAiJHtNRF9VUkx9LyR7a2V5fSIgMj4vZGV2L251bGwgfHwgdHJ1ZQp9CgpDTFVTVEVSX0ROUz0iJChmZXRjaF9tZCBrdWJlZG5zX3N2Y19pcCkiCktVQkVMRVRfRVhUUkFfQVJHUz0iJChmZXRjaF9tZCBrdWJlbGV0LWV4dHJhLWFyZ3MpIgpBUElTRVJWRVJfRU5EUE9JTlQ9IiQoZmV0Y2hfbWQgYXBpc2VydmVyX2hvc3QpIgpLVUJFTEVUX0NBX0NFUlQ9IiQoZmV0Y2hfbWQgY2x1c3Rlcl9jYV9jZXJ0KSIKCiMgT0tFIGJvb3RzdHJhcCBleHBlY3RzIHRoZSBjb250cm9sLXBsYW5lIGhvc3Qgd2l0aG91dCB0aGUgS3ViZXJuZXRlcyBBUEkgcG9ydC4KaWYgW1sgIiR7QVBJU0VSVkVSX0VORFBPSU5UfSIgPX4gXlxbKC4qKVxdKDpbMC05XSspPyQgXV07IHRoZW4KICBBUElTRVJWRVJfRU5EUE9JTlQ9IiR7QkFTSF9SRU1BVENIWzFdfSIKZWxpZiBbWyAiJHtBUElTRVJWRVJfRU5EUE9JTlR9IiA9PSAqOiogXV07IHRoZW4KICBBUElTRVJWRVJfRU5EUE9JTlQ9IiR7QVBJU0VSVkVSX0VORFBPSU5UJSU6Kn0iCmZpCgpbIC1uICIke0NMVVNURVJfRE5TfSIgXSAmJiBleHBvcnQgQ0xVU1RFUl9ETlMKWyAtbiAiJHtLVUJFTEVUX0VYVFJBX0FSR1N9IiBdICYmIGV4cG9ydCBLVUJFTEVUX0VYVFJBX0FSR1MKWyAtbiAiJHtBUElTRVJWRVJfRU5EUE9JTlR9IiBdICYmIGV4cG9ydCBBUElTRVJWRVJfRU5EUE9JTlQKWyAtbiAiJHtLVUJFTEVUX0NBX0NFUlR9IiBdICYmIGV4cG9ydCBLVUJFTEVUX0NBX0NFUlQK
  shapeConfigs:
    - ocpus: 4
      memoryInGbs: 16
  volumeConfig:
    bootVolumeConfig:
      imageConfig:
        imageType: OKEImage
        imageId: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaafyna2ydzlcm5da5qnsikfgkdagwsyrarhy2nvhvkumlgfmnb5e6q
  networkConfig:
    primaryVnicConfig:
      subnetConfig:
        subnetId: ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaa6ol3j3apvbbapaiptxdmqgcrrsefvbldmxfdnm6a44pbbxqhzwdq
      assignPublicIp: true
    secondaryVnicConfigs:
      - subnetConfig:
          subnetId: ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaaldc4iigadfwnr3ckaz5xe3ecgm46ocftpdwst2vupvy72grdpw3a
        ipCount: 8
        skipSourceDestCheck: true
