hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
replicaCount: 1
serviceAccount:
  create: true
  name: "karpenter"
settings:
  clusterCompartmentId: "ocid1.compartment.oc1..aaaaaaaawpw5xpzxhzyhramvfhacgthnjljuojhijewbvm6dxaadsrixs7ya"
  vcnCompartmentId: "ocid1.compartment.oc1..aaaaaaaawpw5xpzxhzyhramvfhacgthnjljuojhijewbvm6dxaadsrixs7ya"
  apiserverEndpoint: "10.0.0.11"
  ociVcnIpNative: true
  ipFamilies:
    - IPv4
